apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: customer-service
  name: customer-service
  namespace: customer
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'customer-service:latest'
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      ref: master
      uri: 'https://github.com/benweizhu/openshift-customer-service.git'
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: 'nodejs:10'
        namespace: openshift
    type: Source
  triggers:
    - imageChange:
        lastTriggeredImageID: >-
          172.30.1.1:5000/openshift/nodejs@sha256:3cc041334eef8d5853078a0190e46a2998a70ad98320db512968f1de0561705e
      type: ImageChange
    - type: ConfigChange
    - generic:
        secret: a360d3ac4c898ac9
      type: Generic
    - github:
        secret: 71900144d2c4c1dd
      type: GitHub